name: artools
description: "Arthur Tools"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  csv: ^6.0.0
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.3.5
  flutter_typeahead: ^5.2.0
  geocode: ^1.0.3
  google_fonts: ^6.2.1
  http: ^1.2.2
  location: ^7.0.1
  syncfusion_flutter_charts: ^27.1.53
  syncfusion_flutter_datagrid: ^27.1.53
  syncfusion_flutter_pdf: ^27.1.53
  syncfusion_localizations: ^27.1.53

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/escudos/
    - assets/images/estádios/
    - assets/images/fundos/
    - assets/images/logos/

  fonts:
    - family: Konstruktor
      fonts:
        - asset: assets/fonts/KonstruktorRegular.ttf
          style: normal
    - family: CS
      fonts:
        - asset: assets/fonts/CounterStrikeRegular.ttf
          style: normal

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#838383"
  image: "assets/images/Logo.png"
  android: true
  ios: false
  web: true

# flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  image_path: "assets/images/Logo.ico"
  adaptative_icon_background: "#838383"
  adaptative_icon_foreground: "assets/images/Logo.ico"
  android: "launcher_icon"
  ios: false
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/Logo.ico"
    background_color: "#838383"
    theme_color: "#838383"